docs_dir: docs/book
site_dir: docs/html
nav:
    - { Home: index.md }
    - { Introduction: v1/intro.md }
    - { Configuration: v1/config.md }
    - { 'Manual Usage': v1/manual.md }
site_name: mezzio-session-cache
site_description: 'PSR-6 session persistence adapter for mezzio-session.'
repo_url: 'https://github.com/mezzio/mezzio-session-cache'
extra:
    project: Mezzio
    project_url: 'https://docs.mezzio.dev'
